### ISSUE TITLE
Error while installing on latest version of OS X 

### ISSUE THREAD

**Issue by MadMartigan** [yoreek/XML-Hash-XS#26]
Hello,

We are seeing the following error when installing 0.59 on OS X.

xh_config.h:25:10: fatal error: 'endian.h' file not found

Perl version 5.38.2
Last successfully installed XML-Hash-XS version: 0.57
Mac terminal launched with rosetta

We have reproduced the error on 3 machines.

**Comment by travis-dd** [comment]
Hello,

In `src/xh_config.h`, changing `include <endian.h>` to`include <machine/endian.h>` allows it to successfully compile on macOS (Sequoia 15.2) on my machine in Terminal, also with Rosetta and perl v5.40.0.

I hope this helps for fix.

Best Regards,

Travis

**Comment by yoreek** [comment]
Hi! Please check v0.63.

**Comment by travis-dd** [comment]
Hello,

Worked like a charm. Thanks so much for your work.

-Travis




cpanm XML::Hash::XS
--> Working on XML::Hash::XS
Fetching http://www.cpan.org/authors/id/Y/YO/YOREEK/XML-Hash-XS-0.63.tar.gz
... OK
Configuring XML-Hash-XS-0.63 ... OK
Building and testing XML-Hash-XS-0.63 ... OK
Successfully installed XML-Hash-XS-0.63 (upgraded from 0.59)
1 distribution installed
